//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Showroom_Management_System.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string ModerNumber { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public string CarName { get; set; }
        public Nullable<double> PriceInput { get; set; }
        public Nullable<int> SeatQuantity { get; set; }
        public string Color { get; set; }
        public string Gearbox { get; set; }
        public string Engine { get; set; }
        public Nullable<double> FuelConsumption { get; set; }
        public Nullable<double> KilometerGone { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Checking { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
